InhaBas/inhabas.com-front

src/board/components/BoardNavi.vue, src/board/pages/Board.vue, src/board/pages/BoardDetail.vue, src/layouts/Main.vue, src/routes/BoardRouter.js
-board에서 axios를 통해 api 연결<각 게시판마다 menuId를 연결 하지 못해 기본적으로 6번에 맞춤>
-동적라우팅을 이용하여 BoardDetail에 api 연결
-created 변수를 넣었을때 정보가 전부 출력되어 일부만 출력되도록 수정 예정
=> [enhancement/#19]

src/routes/index.js
-index.js에서 router 변수를 선언하였고 scrollBehavior 함수를 통해서 router 이동시 top값을 0으로 설정하여 초기화 시켜주었다
=> [enhancement/#27] router 이동시 scrollbar 위치 상단으로 초기화

package-lock.json, package.json, src/board/components/BoardNavi.vue, src/board/pages/Board.vue, src/board/pages/BoardDetail.vue, src/board/pages/BoardRegister.vue, src/routes/BoardRouter.js
-moment.js 모듈을 import하여 dateTime method를 작성하여 지정된 포멧에 맞춰 출력이 되도록 함
-curd 작성 완료[delete는 확인 완료/ post와 put은 400번 에러로 인하여 토큰 작업 완료한 뒤에 다시 테스트 해볼것]
-v-model 태그 하나 추가
=> [Enhancement/#29] created 변수 format에 맞춰 출력

src/common/TopBar.vue, src/routes/BoardRouter.js
- 서버에서 받아온 메뉴타입을 toLowerCase() 를 이용하여 소문자로 변경후 진행
=> [enhancement/#36] "/메뉴타입/메뉴아이디"의 방식으로 게시판 링크 맵핑

src/App.vue, src/assets/css/imageuploadify.min.css, src/assets/css/jquery-te-1.4.0.css, src/assets/css/jquery.tag-editor.css, src/assets/css/templete.css, src/board/pages/Board.vue, src/board/pages/BoardDetail.vue, src/board/pages/ContestBoard.vue, src/common/FooterBar.vue, src/common/ThePaginations.vue, src/common/TopBar.vue, src/routes/BoardRouter.js, src/routes/index.js
-main.vue에서 사용하는 css 파일을 추가함
-페이지네이션 구현 마무리가 안됬습니다...(링크 맵핑하면서 다른 컴포너트도 손봐줘야 할 듯 합니다.)
=> [enhancement/#38] 페이지네이션 구현 실패

src/App.vue, src/assets/css/ibas_contents.css, src/board/pages/Board.vue, src/board/pages/BoardDetail.vue, src/board/pages/BoardRegister.vue, src/board/pages/ContestBoard.vue, src/board/pages/ContestDetail.vue, src/board/pages/ContestRegister.vue, src/budget_application/pages/BudgetApplicationBoard.vue, src/budget_application/pages/BudgetApplicationBoardDetail.vue, src/common/Footer.vue, src/common/Header.vue, src/common/TheHeaderTitle.vue, src/layouts/DefaultLayout.vue, src/layouts/EmptyLayout.vue, src/layouts/Main.vue, src/routes/BoardRouter.js, src/routes/BudgetRouter.js, src/routes/index.js
- 중복되는 컴포넌트 layout 처리 ( DefaultLayout, EmptyLayout.vue )
- layout 처리에 따른 코드 수정 완료
- TopBar -> Header / FooterBar -> Footer 파일 이름 수정
=> [enhancement/49]

src/budget_application/pages/BudgetApplicationBoard.vue, src/budget_application/pages/BudgetApplicationBoardDetail.vue, src/budget_application/pages/BudgetApplicationBoardRegister.vue, src/routes/BudgetRouter.js
- 예산지원 CRUD 처리 완료
- 예산지원신청 승인, 거절, 지급 완료 처리 해주어야 함
=> [enhancement/51]

src/styles/Globalstyles.ts, src/styles/Styled.d.ts, src/styles/theme.ts
Globalstyles.ts, Style.d.ts, theme.ts 생성
=>  Feat: global style, theme 적용

src/styles/assets/A.ts, src/styles/assets/Button.ts, src/styles/assets/Div.ts, src/styles/assets/H.ts, src/styles/assets/Img.ts, src/styles/assets/Input.ts, src/styles/assets/P.ts
A, Button, Div, H, Img, Input, P 태그 생성
=>  Feat: 기본 태그 생성

src/Hooks/useFetch.tsx
에러 메세지는 아래와 같음
Error in fetchData: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
=> Fix: 서버 배포 후 fetch 실패에 따른 코드 변경

src/Components/Component/IBAS/MyInfo/MyNewUserTable.tsx, src/Components/Page/IBAS/MyInfo/ManageUser.tsx, src/Recoil/backState.tsx, src/Recoil/frontState.tsx, src/Types/IBAS/TypeMember.tsx
- 신규회원 GET api 적용
- applicationd으로 이동하는 함수 매개변수 지정 수정
- table check 구현
- 신규회원 권한 변경 api 적용
- 신규 회원 전체 수 적용
- 신규 회원 없을 때 ui 처리 완료
=> Feat/#104 신규회원 관리 

src/Components/Common/HeaderNav.tsx, src/Components/Common/Pagination.tsx, src/Components/Component/IBAS/MyInfo/MyNewUserTable.tsx, src/Components/Component/IBAS/MyInfo/MyUserTable.tsx, src/Components/Page/IBAS/MyInfo/ManageUser.tsx, src/Components/Page/Member/LoginProcess.tsx, src/Components/Page/Member/Signup.tsx, src/Components/Page/Member/SignupQuestion.tsx, src/Hooks/useFetch.tsx, src/Recoil/backState.tsx, src/Recoil/frontState.tsx, src/Types/IBAS/TypeMember.tsx
- 동아리원 GET api 적용
- pagination 적용
- 비활동회원 <-> 활동회원 role 변경 api 적용
=> Feat/#108 재학생 동아리원 관리 기능 구현

src/Hooks/useFetch.tsx
=> [Fix/#114] accessToken === "Token"일 때 처리 주석

src/Components/Component/IBAS/MyInfo/MyNewUserTable.tsx, src/Components/Component/IBAS/MyInfo/MyUserTable.tsx, src/Components/Page/IBAS/MyInfo/MyManageExistUser.tsx, src/Components/Page/IBAS/MyInfo/MyManageNewUser.tsx, src/Components/Page/IBAS/MyInfo/MyManageUser.tsx, src/Layout/HeaderTitleLayout.tsx, src/styles/assets/Button.ts, src/styles/assets/Input.ts
- 신입회원관리 더보기 페이지 완성
- 재학생 회원관리 더보기 페이지 완성
=> [Feat/#112] 더보기 페이지 완성 

src/Components/Common/HeaderNav.tsx, src/Components/Common/HeaderTitle.tsx, src/Recoil/backState.tsx, src/Recoil/frontState.tsx, src/Routes/BoardRoute.tsx, src/Types/TypeCommon.tsx
- headerNav에서 받아온 /menus data로 headerTitle 적용
- /menus data가 없을 경우 /menu/menuId api 호출 하도록 적용
- url 바뀔 때마다 fetch 다시 하는 오류 수정
resolves: #113, #90
=> [feature/#113] headerTitle api 적용

src/Components/Component/IBAS/MyInfo/MyGraduateUserTable.tsx, src/Components/Component/IBAS/MyInfo/MyNewUserTable.tsx, src/Components/Component/IBAS/MyInfo/MyUserTable.tsx, src/Components/Container/MyInfo/MyInfoContainer.tsx, src/Components/Page/IBAS/MyInfo/MyApplication.tsx, src/Components/Page/IBAS/MyInfo/MyManageGraduateUser.tsx, src/Components/Page/IBAS/MyInfo/MyManageUser.tsx, src/Functions/dateFunction.tsx, src/Layout/HeaderTitleLayout.tsx, src/Recoil/backState.tsx, src/Recoil/frontState.tsx, src/Types/IBAS/TypeMember.tsx
- 졸업생 관리 api 적용
- 회원 관리 api 바뀐 것 적용
- 신입생 지원서 보기 구현
- 지원서 내 합불 처리 완료
=> [Feat/#134] 회원 관리 마무리

src/Components/Common/HeaderNav.tsx
- check 가 false 인 경우 access를 signing으로 변경
- signUp/check fetch 의존성 변경
=> [fix/#179] fix: set access string 변경

public/images/attachment_grey.svg, src/Components/Common/DragNDrop.tsx, src/Components/Common/Modal/Modal.tsx, src/Components/Common/Modal/ModalChangeImg.tsx, src/Components/Page/IBAS/MyInfo/MyInfo.tsx, src/Hooks/useFetch.tsx, src/Recoil/frontState.tsx
- DragNDrop 세부 기능 구현
- useFetch media 여부 추가
=> [Feat/#209] 프로필 사진 수정 기능 추가

package-lock.json, src/Components/Page/IBAS/Scholarship/Scholarship.tsx, src/Layout/HeaderNavLayout.tsx
- HeaderNavLayout에 Scholarship 경로 추가
- Page/IBAS 경로에 Scholarship 폴더 추가
- Scholarship 배너 컨텐츠 작성
=> [feat/#213] feat: Scholarship 페이지 추가 및 배너 컨텐츠 작성

src/Components/Component/IBAS/Scholarship/ChangesContent.tsx, src/Components/Component/IBAS/Scholarship/SeeMoreButton.tsx, src/Components/Page/IBAS/Scholarship/Scholarship.tsx, src/Types/IBAS/TypeIBAS.tsx, src/Types/IBAS/TypeScholarship.tsx
1. History UI
- 추후에 자세한 컨텐츠 추가
2. 연혁(Changes) UI
- 연혁 내의 도표 component로 추가
- 더보기 버튼 component로 추가
- 임시로 더미데이터로 채워놓음
- 관련된 타입 추가
=> [feat/InhaBas#220] feat: History, 연혁 UI 추가

src/Components/Component/IBAS/Scholarship/ScholarshipDetailList.tsx, src/Components/Page/IBAS/Scholarship/Scholarship.tsx, src/Types/IBAS/TypeIBAS.tsx
- 후원내용 추가 : 클릭 시 버튼 css 미구현, 더보기와 해당 내용의 navigate 미구현, 추후에 임시 사진을 변경해야 함
- 장학금 사용용도 추가 : 더보기와 해당 내용의 navigate 미구현, 추후에 임시 사진을 변경해야 함
- Thanks for : 상세 내용 추가해야 함
- Contact : 정확한 인적사항 기재해야 함, 추후에 해당 UI 삭제 될 수도 있음
- Type : 상세 내역 컴포넌트를 위한 타입 추가
- Component : ScholarshipDetailList 컴포넌트 추가, 후원 내용과 장학금 사용 용도에서 사용 중
=> [feat/#223] feat: 후원내용, 장학금 사용 용도, Thanks for, contact UI 추가

src/Components/Common/Loading.tsx, src/Components/Page/Board/BoardDetail.tsx, src/Components/Page/Board/BoardList.tsx
- board detail api 의존성 추가
- loading 컴포넌트 제작
=> [feat/#234] board list loading 추가

src/Components/Common/HeaderNav.tsx, src/Components/Common/HeaderTitle.tsx, src/Components/Page/Board/BoardCreate.tsx, src/Components/Page/Board/BoardDetail.tsx, src/Components/Page/Board/BoardList.tsx, src/Routes/BoardRoute.tsx, src/Types/TypeBoard.tsx
- route url 수정
- menu fetch id 수정
- menu click시 url 연결
- boardCreate date 추가
- typeBoard date 요소 추가
=>  [feat/#259] 장학회 api 완성에 따른 코드 수정

src/Components/Common/Modal/ModalBankHistoryDetail.tsx, src/Components/Common/Modal/ModalPostBankHistory.tsx, src/Components/Common/Modal/ModalUpdateBankHistory.tsx, src/Components/Component/IBAS/Bank/BankTable.tsx, src/Components/Page/IBAS/Bank/Bank.tsx
- 상세 내역: 날짜를 YY-MM-DD 형식에서 YYYY-MM-DD로 변경
- Post 모달: 파일 첨부하여 post하는 로직 수정하여 내역 추가 기능 구현 완료
- Update 모달: 사용자가 올린 파일들 DragNDrop에 렌더링하는 코드 추가
- bankTable: 내역에 대해 변경사항이 생길 시 refetch를 활용하여 테이블 업데이트 시키는 코드 추가
- bank: refetch를 활용하여 useEffect를 통해 회계내역 다시 받아오는 코드로 수정
=> [fix/#266] fix: 회계 내역 관련 오류 수정

src/Components/Component/IBAS/BankSupport/BankSupportTable.tsx, src/Components/Page/IBAS/BankSupport/BankSupport.tsx
- dropdown 적용
- 필터 적용
- 페이지네이션 적용
- 테이블 바디 정보 수정
=> [feat/#274] feat: board support list 마무리

src/Components/Component/IBAS/BankSupport/BankSupportTable.tsx, src/Components/Page/IBAS/BankSupport/BankSupport.tsx, src/Components/Page/IBAS/BankSupport/BankSupportDetail.tsx, src/Recoil/backState.tsx, src/Routes/MainRoute.tsx, src/Types/TypeBank.tsx
- bank support delete api 적용 완료
=> [feat/#276] feat: bank support detail api 붙이기

src/Components/Page/IBAS/Scholarship/Scholarship.tsx
- 후원내용 mainUrl 정상적으로 변경
- 하단 div height 값 줄임
=> [fix/#293] fix: 후원내용 컨텐츠 클릭 시 해당 글 조회로 이동하는 데에 문제 해결

src/Components/Component/Board/BoardNavigate.tsx, src/Components/Page/Board/BoardList.tsx
- 클릭 시 해당 게시글 리스트 페이지로 이동하게 처리
- board일 때는 board만, test일때는 test만 보이게 처리
- scholar일 땐 board navigate 안보이게 처리
=> [fix/#297] board navigate 에러 해결

src/Components/Page/IBAS/Bank/Bank.tsx
- Bank의 컨테이너 width를 100%에서 90vw로 변경하여 고정시킴
=> [design/#295] design: 회계내역 연도 변경 시 width 변경 문제 해결

src/Components/Common/HeaderTitle.tsx, src/Hooks/useFetch.tsx
- HeaderTitle: true, false 조건 명시
- useFetch: frontState를 set하는 부분 변경
=> [feat/#320] fix: 비로그인 시 페이지 접근 불가 로직 수정

src/Components/Common/HeaderNav.tsx, src/styles/theme.ts
- HeaderNav 종모양 아이콘 주석 처리
- HeaderNav 안의 profile 사진 border color를 role에 따라 분기 처리
- theme에 #ffc107 색상 yellow로 추가
=> [design/#331] design: HeaderNav 디자인 수정

src/Routes/BoardRoute.tsx
=> [feat/#320] fix: BoardRoute의 alert 로직 수정(무한 alert 오류 수정)

src/Functions/authFunctions.tsx
- authFunctions의 role 판단 코드에 login 하였을 때 조건 추가
=> [feat/#320] fix: 예산신청내역 무한 렌더링 해결

src/Components/Common/HeaderNav.tsx
header nav에 honor 경로 접근 불가 로직 추가
=> [feat/#332] feat: 명예의 전당 페이지 접근 불가 로직 추가

src/Components/Common/HeaderTitle.tsx
- pathName에 staff가 포함되지 않는 경우에만 fetchTitle을 실행
=> [feat/#320] fix: 회원 관리 페이지 진입 시 404에러 뜨는 문제 해결

src/Components/Component/Contest/ContestInfo.tsx, src/Components/Page/Board/BoardList.tsx, src/Components/Page/IBAS/Contest/Contest.tsx, src/Components/Page/IBAS/Contest/ContestDetail.tsx
- ContestInfo : dday 활용하여 마감, 오늘마감, 진행중 상태 표시 추가
- BoardList : Contest fetch 부분 필요없는 주석 제거
- Contest : 전체보기, 진행중 필터링을 위한 드롭박스 추가
- ContestDetail : writerId 요소 추가
=> [feat/#383] feat: 공모전 모집 상태 추가, 필터링 드롭박스 추가

src/Components/Common/HeaderNav.tsx, src/Components/Page/IBAS/Activity/Activity.tsx, src/Components/Page/IBAS/Activity/ActivityCreate.tsx, src/Components/Page/IBAS/Activity/ActivityDetail.tsx, src/Routes/MainRoute.tsx
- HeaderNav : 사용 불가 기능에서 activity 제거
- Activity : 동아리 활동 게시판 ui, 기능 추가
- ActivityCreate : 동아리 활동 게시글 추가 ui, 기능 추가
- ActivityDetail : 동아리 활동 상세 페이지 추가 ui, 기능 추가
- MainRoute : 동아리 활동 상세 페이지, 수정 페이지 라우팅 추가
=> [feat/#403] feat: 동아리 활동 기능 구현

src/Components/Page/Board/BoardList.tsx, src/Components/Page/IBAS/Activity/Activity.tsx, src/Components/Page/IBAS/Contest/Contest.tsx, src/Recoil/frontState.tsx
- BoardList : api 수정에 따른 공모전 fetchUrl 재설정
- Contest : dropdown 수정
- frontState : 공모전 정렬 방식 변수 추가
=> [feat/#383] api 수정에 따른 수정

src/Components/Component/Contest/ContestInfo.tsx
=> [feat/#383] design: 공모전 페이지 진행 상태 css 수정

src/Components/Component/IBAS/Activity/ActivityCard.tsx, src/Components/Page/IBAS/Activity/Activity.tsx, src/Components/Page/IBAS/Activity/ActivityCreate.tsx, src/Components/Page/IBAS/Activity/ActivityDetail.tsx, src/Types/IBAS/TypeIBAS.tsx
- Activity: ActivityInterface 분리, 동아리 활동 게시판 등록 권한 설정
- ActivityCreate: ActivityDetailInterface 분리
- ActivityDetail: Carousel 기능 추가, 게시글 수정 삭제 시에 권한 추가
- TypeIBAS: ActivityDetailInterface, ActivityInterface 추가
- ActivityCard: Activity 페이지 컴포넌트 추출하여 추가
=> [feat/#403] 동아리 활동 게시판 완성

src/Components/Common/Comment.tsx, src/Components/Common/Loading.tsx, src/Components/Component/IBAS/MyInfo/MyBoardTable.tsx, src/Components/Container/MyInfo/MyBankSupportContainer.tsx, src/Components/Page/Board/BoardCreate.tsx, src/Components/Page/Board/BoardDetail.tsx, src/Components/Page/Board/BoardList.tsx, src/Components/Page/IBAS/Activity/ActivityCreate.tsx, src/Components/Page/IBAS/BankSupport/BankSupport.tsx, src/Components/Page/IBAS/BankSupport/BankSupportDetail.tsx, src/Components/Page/IBAS/Contest/ContestCreate.tsx
- 댓글 수정사항 반영 바로 안되는 오류 해결
- loading height 수정 및 그에 따른 변경사항 적용
=> [Fix/#413] 댓글 수정사항 반영 바로 안되는 오류 해결 fix

src/Components/Page/IBAS/Activity/ActivityCreate.tsx, src/Components/Page/IBAS/Activity/ActivityDetail.tsx, src/Types/IBAS/TypeIBAS.tsx
- ActivityCreate: 파일 업로드 시 1개 이상의 이미지 파일 필요
- ActivityDetail : 파일 다운로드 목록 추가, 운영진 삭제 버튼만 보이게
- TypeIBAS : otherFiles 속성 추가
=> [fix/#434] fix: 동아리 활동 피드백 반영

src/Components/Common/CommentList.tsx, src/Components/Page/IBAS/Activity/ActivityDetail.tsx, src/Types/TypeCommon.tsx
- TypeCommon : token 속성 추가
- CommentList : 토큰 속성에 따라 댓글 get 요청하는 조건문 추가
- ActivityDetail : 댓글 토큰 없이 패치
=> [fix/#434] fix: 비로그인 시 동아리 활동 댓글 보이게 수정

src/Components/Page/Board/BoardList.tsx
- checkWritingAuthorization에 contest 추가
=> [fix/#457] fix: 공모전 등록 버튼 보이게 수정

src/Components/Component/Contest/ContestInfo.tsx, src/Components/Page/IBAS/Contest/ContestCreate.tsx, src/Functions/dateFunction.tsx
- fix: border 변경
- fix: 공모전 end 시간 23:59:59로 변경
- fix: 공모전 게시글 등록 에러 처리 ( 모집 마감일 -> 오늘 이후 )
=> [fix/#474] 공모전 feedback 반영

src/Components/Component/IBAS/MyInfo/MyCommentTable.tsx, src/Components/Container/MyInfo/MyBoardContainer.tsx, src/Recoil/backState.tsx, src/Types/TypeCommon.tsx
- MyCommentTable : 댓글 테이블 완성
- MyBoardContainer : 주석 처리 해제
- backState : myCommentsInfo state 추가
- TypeCommon : myCommentInterface 추가
=> [feat/#479] feat: 내 정보 댓글 테이블 구현

src/Components/Component/IBAS/MyInfo/MyCommentTable.tsx, src/Components/Container/MyInfo/MyBoardContainer.tsx, src/Components/Page/Board/BoardList.tsx, src/Hooks/useFetch.tsx, src/Recoil/backState.tsx, src/Types/TypeCommon.tsx
- checkWritingAuthroization의 활동 회원 부분에 alpha, beta 추가
=> [fix/#486] 알파, 베타테스터 게시글 작성 버튼 정상적으로 나타나게 처리

src/Components/Component/IBAS/MyInfo/MyCommentTable.tsx, src/Components/Container/MyInfo/MyBoardContainer.tsx, src/Components/Page/IBAS/Contest/Contest.tsx, src/Hooks/useFetch.tsx, src/Recoil/backState.tsx, src/Types/TypeCommon.tsx
- 기존에 BaordList에서 공모전 게시판의 게시글 추가 버튼을 보이게 했음
- ui 수정을 위해 Contest 파일 안에 게시글 추가 버튼을 넣은 후 권한 처리를 해주지 않아 생긴 문제였고, 처리 완료
=> [fix/#488] 공모전 게시판 게시글 추가 버튼 활동 회원 이상만 보이게 처리

src/Components/Page/Board/BoardCreate.tsx, src/Components/Page/Board/BoardDetail.tsx, src/Routes/BoardRoute.tsx
- BoardCreate : 장학회 게시판 update 시에 후원 날짜 default로 적용
- BoardDetail : 장학회 게시판 detail에 지급일 표시
- BoardRoute : 장학회 update 라우팅 처리
=> [feat/#494] 장학회 게시판 update, 후원 날짜 표시 추가

src/Components/Page/IBAS/Contest/ContestDetail.tsx
- 공모전 ui 변경
- 주제 길어지면 ui 깨지는 오류 해결
=> [design/#499] 공모전 주제 ui 변경 및 주제 길면 ui 깨지는 오류 해결

src/Components/Component/IBAS/MyInfo/MyCommentTable.tsx, src/Types/TypeCommon.tsx
- MyCommentTable : 댓글 삭제 시에 isDeleted 변수를 사용하여 삭제 표시
- TypeCommon : myCommentInterface에 isDeleted 추가
=> [fix/#498] 내가 작성한 댓글에 댓글 삭제 여부 표시

src/Components/Page/Member/Signup.tsx
=> [fix/#503] 회원가입 전화번호 미기입 시 alert 두번 뜨는 현상 해결

src/Hooks/useFetch.tsx
=> [fix/#507] 토큰 재발급 시 alert 뜨는 문제 해결

src/Components/Page/Board/BoardCreate.tsx, src/Routes/BoardRoute.tsx
- BoardCreate : writerId 비교 로직 추가, writerId가 다르다면 alert 후 이전 페이지로 이동
- BoardRoute : create 페이지 권한 로직 삭제
=> [fix/#505] 권한 변경 후에도 본인이 작성한 글 수정, 삭제 가능

src/Components/Common/DragNDrop.tsx
=> [design/#513] DragNDrop 스크롤바 추가

src/Components/Common/Modal/ModalPostBankHistory.tsx, src/Components/Common/Modal/ModalUpdateBankHistory.tsx, src/Components/Component/IBAS/Bank/BankTable.tsx, src/Components/Page/IBAS/Bank/Bank.tsx
- ModalPostBankHistory : T00:00:00 올바르게 처리
- ModalUpdateBankHistory : Loading bar 추가
- BankTable : 본인이 작성하지 않은 회계내역 수정 삭제 불가하게 바꿈
- Bank : fetchData 요소에 writerId 추가
=> [fix/#515] 회계내역 피드백 반영

src/Components/Common/Modal/ModalHistory.tsx, src/Components/Common/Modal/ModalPostBankHistory.tsx, src/Components/Common/Modal/ModalScholarshipHistory.tsx, src/Components/Common/Modal/ModalUpdateBankHistory.tsx, src/Components/Page/Board/BoardCreate.tsx, src/Components/Page/IBAS/BankSupport/BankSupportCreate.tsx, src/Components/Page/IBAS/Contest/ContestCreate.tsx, src/Components/Page/Lecture/LectureCreate.tsx, src/styles/assets/Input.ts
- Date의 변수명 변경 및 참조 변수명 변경
- ModalPostBankHistory: 미래 시점 등록 시 alert 기능 추가
- ModalUpdateBankHistory: 미래 시점 등록 시 alert 기능 추가
=> [feat/#519] feat: 회계내역 날짜 미래 시점 등록 시 alert, Input의 Date 이름 변경

src/Components/Page/Board/BoardDetail.tsx, src/Components/Page/IBAS/Activity/ActivityDetail.tsx, src/Components/Page/IBAS/Contest/ContestDetail.tsx
=> [fix/#530] fix: textviewer 적용안된 부분 적용하기

src/Components/Common/DragNDrop.tsx, src/Components/Page/IBAS/BankSupport/BankSupportCreate.tsx, src/Components/Page/IBAS/BankSupport/BankSupportDetail.tsx
- DragNDrop 수정
- BankSupportCreate 수정
- BankSupportDetail UI 수정
=> [fix/#542] fix: 예산지원신청 증빙자료 첨부 오류

src/Components/Common/Modal/ModalPostBankHistory.tsx, src/Components/Page/IBAS/BankSupport/BankSupportCreate.tsx
- Date 객체를 통하여 이전 시점인지를 체크하고 미래 시점이라면 alert
=> [fix/#546] 회계내역, 예산지원신청 날짜 현재보다 이전 시점만 가능하게 적용

src/Components/Common/Carousel.tsx
=> [design/#544] design: ArrowButton left, right 속성 삭제
